export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TASK_MANAGER_ROUTE = '/'
export const USERS_TASKS_ROUTE = '/usersTasks'
export const PROJECTS_ROUTE = '/projects'
